### ISSUE TITLE
Reconnect does not work

### ISSUE THREAD

**Issue by tdmowrer** [Unity-Technologies/com.unity.mobile.logcat#104]
Package version 1.1.1 (2019.3 verified), macOS, Unity 2019.3.14f1

If you run a different version of `adb` from the command line, it disconnects the package version of logcat (as expected). However, even after ending the cmd line adb, the "Reconnect" button in this package appears to have no effect, even after redeploying the app to device.

**Edit** After restarting the Editor, it connected again, but Editor restart should not be required.

**Comment by todi1856** [comment]
@tdmowrer is this still an issue, I cannot reproduce this, if you mange to reproduce it again, please check Internal Log in top right corner of logcat window for more information

**Comment by tdmowrer** [comment]
Will do. Thanks for looking into it!
