### ISSUE TITLE
Tag is not saved

### ISSUE THREAD

**Issue by Alexees** [Unity-Technologies/com.unity.mobile.logcat#108]
Closing and opening the Android Logcat tab does not persist tags
Tested this with latest 1.2 preview.

**Comment by todi1856** [comment]
@Alexees could you be more specific, there are multiple tabs in Unity, and Logcat itself. A screenshot/video would help.

**Comment by Alexees** [comment]
This one here gets deleted whenever this window goes away (tab close, Editor close)
![image](https://user-images.githubusercontent.com/32508825/85692614-d79e8180-b6d5-11ea-881c-2603de5d362e.png)

**Comment by todi1856** [comment]
Oh you mean the search field. I see
