### ISSUE TITLE
[Bug] Logcat doesn't work with wireless debugging

### ISSUE THREAD

**Issue by AgrMayank** [Unity-Technologies/com.unity.mobile.logcat#142]
- Logcat package doesn't work when devices are connected via wireless debugging.
- It instead disabled wireless debugging (connected via ADB command manually in terminal) on Android when opened.
- The menu to connect the device over with IP address also doesn't work as in the screenshots below and wrongly shows already connected to the device, but the dropdown remains empty.

![image](https://user-images.githubusercontent.com/26793209/142634389-63f877e8-16b7-4658-a115-fa38f17480bb.png)
![image](https://user-images.githubusercontent.com/26793209/142631468-db6045ae-fde1-4e11-8e17-11d3f82ad11a.png)

**Comment by Rubix1991** [comment]
Your port is strange, usually it's 5555, how did you get this port and which device are you talking about ?

**Comment by todi1856** [comment]
Your port is strange, usually it's 5555, how did you get this port and which device are we talking about ?

**Comment by AgrMayank** [comment]
> 

I got it from the Wireless debugging options withing Developer Options in Android (Samsung A50).

**Comment by todi1856** [comment]
Can you open terminal and do manually adb logcat and see if it works

**Comment by AgrMayank** [comment]
> 

Yes, manually ADB logs work fine via terminal but not in logcat package.
Even Unity build settings don't recognize any wirelessly connected ADB devices whereas I can see them clearly in ```adb devices``` after connecting.

https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+

**Comment by todi1856** [comment]
I've looked a bit, and you're correct in some sense. Logcat package doesn't know how to pair with the device.

But if you'll open terminal and do pairing manually, it works fine. So basically:
* Open terminal
* adb pair <ip>:<port1> 
* enter code
* you can do adb connect <ip>:<port2> from terminal or from logcat package via Other connections button and it should connect.

**One thing to notice the port for adb pair and adb connect is different.**

After that's done, logcat package starts to work fine

**Comment by AgrMayank** [comment]
> I've looked a bit, and you're correct in some sense. Logcat package doesn't know how to pair with the device.
> 
> But if you'll open terminal and do pairing manually, it works fine. So basically:
> 
> * Open terminal
> * adb pair :
> * enter code
> * you can do adb connect : from terminal or from logcat package via Other connections button and it should connect.
> 
> **One thing to notice the port for adb pair and adb connect is different.**
> 
> After that's done, logcat package starts to work fine

That's weird because I tried ADB pair and ADB connect, and it works fine on Terminal but if I try to open logcat after pairing & connecting via terminal, then it disconnects. Manually connecting via the logcat device settings shows it is already paired or failed to connect. But in the device dropdown, it shows disconnected. See the first screenshots attached. 

FYI I tried both the ADB pair and ADB connect IP & ports but none worked.

So I was wondering what went wrong. I tried a bunch of things like the steps you mentioned but nothing worked.

> Unity 2020.3.22f1
> Latest ADB Logcat Package
> Windows 11

**Comment by todi1856** [comment]
I can only guess you're using different ADB - for pairing and the one which Unity uses together with logcat package.

Since the adb connection lives as long as adb process lives. When you switch to Unity, Unity ensures that adb process from SDK set in Unity preferences is used, if Unity detects a different adb, it will kill, along with all connections

**Comment by AgrMayank** [comment]
> I can only guess you're using different ADB - for pairing and the one which Unity uses together with logcat package.
> 
> Since the adb connection lives as long as adb process lives. When you switch to Unity, Unity ensures that adb process from SDK set in Unity preferences is used, if Unity detects a different adb, it will kill, along with all connections

I'm using the ADB connect IP & ports. I tried with the ADB pair ports as well which resulted in pairing unsuccessful message on my phone.

Weirdly, I am getting a message saying I'm already connected to the IP but it still shows disconnected in the devices menu for some reason.

Also, I didn't find any ADB menu in Preferences so I guess I'll have to use manual connection via terminal until it gets fixed.

**Comment by todi1856** [comment]
I think you might misunderstood me. Could you copy paste screenshots:
* from Unity's Preferences->External Tools, where Android SDK path is specified
* from terminal showing how you do adb pair

If you're using different SDKs then it's expected for connection to be dropped

**Comment by AgrMayank** [comment]
> I think you might misunderstood me. Could you copy paste screenshots:
> 
> * from Unity's Preferences->External Tools, where Android SDK path is specified
> * from terminal showing how you do adb pair
> 
> If you're using different SDKs then it's expected for connection to be dropped

## Preferences tools 

![image](https://user-images.githubusercontent.com/26793209/142848738-d94be220-9d41-4d44-ad98-4c83da9d2495.png)
![image](https://user-images.githubusercontent.com/26793209/142848691-23e6afa1-552e-454a-b1ef-634ed517426e.png)

## ADB Terminal

1. ![image](https://user-images.githubusercontent.com/26793209/142849280-c0db41c2-8bda-47b9-8112-af8fac9a6730.png)
2. ![image](https://user-images.githubusercontent.com/26793209/142849489-82a2831e-9381-490f-9772-c639c19cc373.png)
3. ![image](https://user-images.githubusercontent.com/26793209/142849512-5283fbb3-e3fc-4634-8e32-135c40269c4f.png)
4. ![image](https://user-images.githubusercontent.com/26793209/142849534-afba0efc-bce9-46f8-86e1-61019dad1394.png)

As you can see, it is not showing in the dropdown.

**Comment by todi1856** [comment]
The reason for that, like I said, you're using different adb for pair. You see that message in the terminal
"adb server doesn't match this client", that means when you invoke adb in terminal, the previous adb instance is killed along with all the command you entered previously.

Just try this, from logcat windows, go to Tools->Open terminal, and enter adb pair/connect commands the terminal opened by logcat package, then the logcat should start seeing your device, and you should be able to build and run to it from Unity

**Comment by AgrMayank** [comment]
Thanks, @todi1856 ! This fixed the issue. I was opening the terminal manually instead of the _Open Terminal_ option. Build and run is working fine as well. It's a great help to do debugging without cables.
