### ISSUE TITLE
Backslash in regex field will block adb connection

### ISSUE THREAD

**Issue by sergiodl-naist** [Unity-Technologies/com.unity.mobile.logcat#147]
* Unity 2021.2.7f1
* Android Logcat 1.2.3
* Linux Mint 20.3

1. Wrote in regex search field: DEBUG:\
2. Froze up
3. Disconnected from device
4. Logcat window will no longer connect to the device even if it's recognized. There is no way to remove "DEBUG:\\" from the search field (grayed out field, regex button also grayed out).
5. Closing Logcat window, closing the project, unplugging device, "Reset Packages to Default", removing the package, etc, will not make a difference.
6. Unity Console filled with errors the moment Logcat window is open, they won't stop even after Logcat window is closed. Two repeating errors: "No process is associated with this object \n UnityEngine.Debug:LogError(object)" and "InvalidOperationException: No process associated with this object. \n System.Diagnostics.Process.EnsureState (System.Diagnostics.Process+State state)".

It all begins with this error in the console:
```
Win32Exception: ApplicationName='/path/to/Unity/2021.2.7f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/platform-tools/adb', CommandLine='-s DeviceCode logcat -v year *:V --regex "DEBUG:\"', CurrentDirectory='', Native error= Success
System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <6d066b05df624e3299ce5c89aeae679f>:0)
System.Diagnostics.Process.Start () (at <6d066b05df624e3299ce5c89aeae679f>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
Unity.Android.Logcat.AndroidLogcatMessageProvider.Start () (at Library/PackageCache/com.unity.mobile.android-logcat@1.2.3/Editor/AndroidLogcatMessageProvider.cs:78)
Unity.Android.Logcat.AndroidLogcat.Start () (at Library/PackageCache/com.unity.mobile.android-logcat@1.2.3/Editor/AndroidLogcat.cs:183)
Unity.Android.Logcat.AndroidLogcatConsoleWindow.StartLogcat () (at Library/PackageCache/com.unity.mobile.android-logcat@1.2.3/Editor/AndroidLogcatConsoleWindow.cs:813)
Unity.Android.Logcat.AndroidLogcatConsoleWindow.RestartLogCat () (at Library/PackageCache/com.unity.mobile.android-logcat@1.2.3/Editor/AndroidLogcatConsoleWindow.cs:789)
Unity.Android.Logcat.AndroidLogcatConsoleWindow.SelectPackage (Unity.Android.Logcat.PackageInformation newPackage) (at Library/PackageCache/com.unity.mobile.android-logcat@1.2.3/Editor/AndroidLogcatConsoleWindow.cs:604)
Unity.Android.Logcat.AndroidLogcatConsoleWindow.OnUpdate () (at Library/PackageCache/com.unity.mobile.android-logcat@1.2.3/Editor/AndroidLogcatConsoleWindow.cs:280)
Unity.Android.Logcat.AndroidLogcatRuntimeBase.OnUpdate () (at Library/PackageCache/com.unity.mobile.android-logcat@1.2.3/Editor/AndroidLogcatRuntime.cs:94)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /home/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:356)

```

So my guess is that the backslash is escaping the double quotes of the --regex parameter and erroring out the command

**Comment by todi1856** [comment]
Hmph, if you're blocked, you can reset the settings by deleting logcat settings in <project>\UserSettings

**Comment by todi1856** [comment]
It will be fixed by upcoming version (no ETA), https://github.com/Unity-Technologies/com.unity.mobile.logcat/pull/143 since filtering will be done by package instead of logcat command itself
