### ISSUE TITLE
Incorrect parsing of data on device

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/com.unity.mobile.logcat#15]
Device repro: Huawei Mate P20 Pro
![image (1)](https://user-images.githubusercontent.com/568752/59616226-af785c00-912c-11e9-9d47-8b15b2718de8.png)
![image (2)](https://user-images.githubusercontent.com/568752/59616225-af785c00-912c-11e9-849f-f27a1634097a.png)

`0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 10:02:20.246 1894 2083 E : NcChipChr write_WifiChr_reason, errorcode:909009520 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 10:02:20.246 1894 2083 E : NcChipChr chr_open_dev(): open succ 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 10:02:20.246 1894 2083 E : write_WifiChr_reason, ret=0 2019/02/19 10:02:20.402 609 609 Info chatty: uid=1000(system) /vendor/bin/pmom_cat expire 12 lines 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 10:02:20.689 1894 2082 E : NcChipChr chr_read_error() errno:9 2019/02/19 10:02:20.993 1894 2082 Debug CommInfo: support chipchr 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 10:02:20.993 1894 2082 E : NcChipChr chr_read_error(): in 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 10:02:20.993 1894 2082 E : NcChipChr chr_open_dev(): open succ`

`0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:05.489 2985 2995 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008] 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:07.181 2833 2833 I InCall - CallList: no active call 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:07.577 5358 5358 D HwLBSService DeviceStatusMonitor: DEVICE_SCREEN_STATE_OFF 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:07.577 5358 5405 D HwLBSService HigeoLocationManager: receive message: 8 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:07.577 5358 5405 D HwLBSService FusionDaemonManager: sendScreenState state : 0 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:07.577 5358 5405 D HwLBSService FusionDaemonManager: Get getIFusdLbsService service not null. 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:10.131 2833 2833 I InCall - CallList: no active call 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:10.213 5358 5358 D HwLBSService DeviceStatusMonitor: DEVICE_SCREEN_STATE_ON 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:10.213 5358 5405 D HwLBSService HigeoLocationManager: receive message: 7 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:10.213 5358 5405 D HwLBSService FusionDaemonManager: sendScreenState state : 1 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:10.213 5358 5405 D HwLBSService FusionDaemonManager: Get getIFusdLbsService service not null. 2019/02/19 12:57:10.213 812 812 Warn FusionDaemon: (fd_on_lbs_msg:655):Maybe gnss has not start. 2019/02/19 12:57:10.213 812 812 Info FusionDaemon: (sendScreenState:147):FusdLbs: sendScreenState. 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:10.213 5358 5405 D HwLBSService HigeoLocationManager: HwLBSService version: 9.0.2.0921 2019/02/19 12:57:10.217 3048 6204 Warn ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1876 android.content.ContextWrapper.bindService:698 com.huawei.nb.dataservice.dsclient.RemoteServiceConnection.open:90 com.huawei.nb.dataservice.dsclient.DataServiceProxy.connect:105 com.huawei.nb.dataservice.rsclient.internal.RemoteRuleService.start:27 2019/02/19 12:57:10.218 26824 26824 Info [10.2.2.301]CloudAlbum.SyncStrategy: setPowerConsumptionTooFast: false 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:57:10.220 26824 26834 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]`

Device repro: Samsung Galaxy J5

`0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 05:19:56.502 699 1191 I : CalibrateActuatorDriverData [AFDBG] AF OTP Infinity:284 Macro:876 -> inf:225 macro:1053 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 05:19:56.502 699 1191 I : StepToDAC [AFDBG] step:364 dac:297 actuatorName:imx519_lc898217xc OIS shift X:5 shift Y:2 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 05:19:56.530 699 1426 I : CAFIOUtil() m_EnableLCR:1`

`0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 05:23:05.789 712 712 I QTI PowerHAL: Got set_interactive hint on= 1, count= 19 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 05:23:05.789 712 712 E QTI PowerHAL: Error opening /sys/kernel/hbtp/display_pwr: No such file or directory`

`0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 05:23:16.110 712 712 I QTI PowerHAL: Got set_interactive hint on= 0, count= 20 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 05:23:16.111 712 712 E QTI PowerHAL: Error opening /sys/kernel/hbtp/display_pwr: No such file or directory`

Huawei Nexus 6P: `0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 11:36:26.748 1552 6084 D : oem_qmi_lib:come into oem_qmi_common_stream_from_modem_len --->modem 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 11:36:26.749 1552 6084 D : oem_qmi_lib:oem_qmi_cmd: Send to server passed!! 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 11:36:26.749 582 1489 D : oem-qmi: Connection accepted 2019/02/19 11:36:26.749 799 3589 Warn ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=3763, uid=10012 that is not exported from uid 10059 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 11:36:26.749 582 1489 D : oem-qmi: Waiting to accept connection 2019/02/19 11:36:26.755 22776 22776 Info chatty: uid=10075(u0_a75) com.google.android.youtube expire 35 lines 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 11:36:26.755 1552 6084 D : oem_qmi_lib:output 0 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 11:36:26.755 1552 6084 D : oem_qmi_lib:rapi_event_type=10057, qmi_ret=0, return_status=1. 2019/02/19 11:36:26.756 3763 23141 Info chatty: uid=10012(u0_a12) com.google.android.gms expire 7 lines`

Samsung Galaxy S3: `02/19 12:46:36.530 2217 2917 Debug Netd: getNetworkForDns: using netid 502 for uid 10058 01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:36.530 7742 7786 E : Unable to get Object Class and clearing cls 2 [int check_gadget_reset_status() 649] 02/19 12:46:36.530 7742 7786 Error MTPJNIInterface: Getting gadget reset status1 01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:36.530 7742 7786 E : [check_gadget_reset_status 760] gadget reset is done 01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:36.530 7742 7786 D : *****Starting mtp_io() 01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:36.530 7742 7786 D : [mtp_start_io] source_thread Creation 01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:36.530 7742 7786 D : [mtp_start_io] sink_thread Creation 01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:36.530 7742 7786 D : [mtp_start_io:391] sink thread created so set th_sink`

`02/19 11:43:36.675 3459 3664 Info NetworkClient: SIZE :43 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:36.680 3483 3494 E : Device driver API match 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:36.680 3483 3494 E : Device driver API version: 23 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:36.680 3483 3494 E : User space API version: 23 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:36.680 3483 3494 E : mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Wed Oct 9 21:05:57 KST 2013 02/19 11:43:36.690 2344 2837 Verbose VibratorService: useVibetonz: true`

`01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:43.635 4455 4455 E : Samsung TTS Engine - initialize() : Samsung TTS Engine (released - 201302151) 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:43.635 4455 4455 E : Samsung TTS Engine - initialize() : ro.product.manufacturer - samsung 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:43.765 4455 4466 E Samsung TTS: onIsLanguageAvailable() - lang : eng, country : USA, variant : , iResult : 1 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:43.765 4455 4523 E Samsung TTS: onIsLanguageAvailable() - lang : eng, country : USA, variant : , iResult : 1 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:43.765 4455 4523 E Samsung TTS: onLoadLanguage() - LANG_COUNTRY_AVAILABLE 01/01 00:00:00.000 -1 -1 Info : 02-19 11:43:43.765 4455 4523 E Samsung TTS: onLoadLanguage() - lang : eng, country : USA, variant : f01`

Meizu PRO 6 Plus `2019/02/19 12:43:36.325 2964 3092 Debug AlarmManager: set alarm to RTC 3-324931245-12:46:25 2019/02/19 12:43:36.329 3391 3391 Debug b: onReceive: onReceive: android.net.wifi.STATE_CHANGE 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:43:36.332 3775 3775 D [ SHANNON_IMS_SERVICE]: ********************************************************* 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:43:36.332 3775 3775 D [ SHANNON_IMS_SERVICE]: [CAUTION] Code flow is modified to test ePDG connectivity 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:43:36.332 3775 3775 D [ SHANNON_IMS_SERVICE]: ********************************************************* 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:43:36.332 3775 3775 D [ SHANNON_IMS_SERVICE]: WiFi connectivity broadcast received with action : android.net.wifi.STATE_CHANGE 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:43:36.332 3775 3775 I [ SHANNON_IMS_SERVICE]: CONNECTIVITY_CHANGE broadcast received with action : android.net.wifi.STATE_CHANGE 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:43:36.332 3775 3775 I [ SHANNON_IMS_SERVICE]: NETWORK_STATE_CHANGED_ACTION: mIsWifiConnected=false 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:43:36.332 3775 3775 I [ SHANNON_IMS_SERVICE]: Wifi state is either enabling or disabled.. 2019/02/19 12:43:36.334 3130 3692 Debug WifiSignalController: handleBroadcast enabling=false,disabling=false,connecting=false`

Samsung Galaxy S8: `2019/02/19 12:45:44.613 3780 4554 Warn EngineeringModeService: getStatus(iS) Failed to get EM Server time. Use current value 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:45:44.615 3148 3158 I : Read from block 2019/02/19 12:45:44.617 3148 3158 Info chatty: uid=0(root) /system/bin/vold identical 2 lines 0001/01/01 00:00:00.000 -1 -1 Info : 2019-02-19 12:45:44.617 3148 3158 I : Read from block 2019/02/19 12:45:44.625 3780 3791 Debug SecContentProvider: called from android.uid.system:1000`

Samsung Galaxy Note 10.1 Tablet: `02/19 12:45:34.535 2817 2926 Debug PointerIcon: setHoveringSpenCustomIcon IconType is same.1 02/19 12:45:34.545 3042 3042 Debug SecVolumePanel.0afee4ee: onSliderVisibilityChanged(stream=-200, visi=0) 01/01 00:00:00.000 -1 -1 Info : 02-19 12:45:34.545 3241 3411 I : PLATFORM VERSION : JB-MR-2 02/19 12:45:34.555 3241 3411 Debug libEGL: eglInitialize EGLDisplay = 0x9c6ffc54`

`01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:18.470 6710 6754 I GFX raster: took 0.435042ms for 96*96 texture 0 01/01 00:00:00.000 -1 -1 Info : 02-19 12:46:18.505 6710 6754 I GFX raster: took 0.341834ms for 96*96 texture 0`

`02/19 12:45:34.650 3440 3440 Info SELinux: Function: selinux_compare_spd_ram, SPD-policy is existed. and_ver=SEPF_SM-P600_5.1.1 ver=51 02/19 12:45:34.650 3440 3440 Info SELinux: Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-P600_5.1.1_0070 01/01 00:00:00.000 -1 -1 Info : 02-19 12:45:34.650 3241 3278 I GFX construct_block_size_descriptor_2d second part: took 15.589168ms for 0*0 texture 0 02/19 12:45:34.650 3440 3440 Error SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL 02/19 12:45:34.650 3241 3411 Debug OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 8192 02/19 12:45:34.650 3241 3411 Debug OpenGLRenderer: Enabling debug mode 0 01/01 00:00:00.000 -1 -1 Info : 02-19 12:45:34.655 3241 3278 I GFX generate_partition_tables: took 8.340126ms for 0*0 texture 0 01/01 00:00:00.000 -1 -1 Info : 02-19 12:45:34.675 3241 3278 I GFX raster: took 44.010918ms for 144*144 texture 0 02/19 12:45:34.705 3454 3454 Error Zygote: MountEmulatedStorage()`

Xiaomi MI MAX `01/01 00:00:00.000 -1 -1 Info : 02-19 08:51:47.477 536 2683 D : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file 01/01 00:00:00.000 -1 -1 Info : 02-19 08:51:47.478 536 2683 D : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file 02/19 08:51:47.478 536 2683 Debug ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE 01/01 00:00:00.000 -1 -1 Info : 02-19 08:51:47.478 536 2683 D : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file`

Package version: 0.2.1 - preview Tested with: 2019.2.0a5

**Comment by todi1856** [comment]
FIxed

**Comment by Dvalin21** [comment]
How did you fix it?

**Comment by todi1856** [comment]
> How did you fix it?

Adjusted the regex how the message is parsed
