### ISSUE TITLE
Regex button does nothing

### ISSUE THREAD

**Issue by WashingMachinae** [Unity-Technologies/com.unity.mobile.logcat#26]
Clicking regex should enable parsing the search field as a regex expression, but the input is the same regardless of the button being enabled or not. 

Tested with: 2019.3.0a8
Package version: 0.2.7
commit c231874b51b245240bad59f3336b733cf2ae6302

**Comment by todi1856** [comment]
@WashingMachinae  When testing this fix, be sure to test on Android 6.0 and Android 7.0 devices.
