### ISSUE TITLE
After some very large amount of logcat entries, the lines break down

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#33]
![GlitchyLogcat](https://user-images.githubusercontent.com/43995107/60872492-6b650c80-a23d-11e9-8f50-96b968beb959.gif)

Also, when searching in the "search" field, the entries get flushed and searched up to the max of the device logs, rather than what was already saved over the last time period. 
Basically, the log you were running for 3 days gets dumped and you only get the max amount of lines searched within the device log. This might deserve a separate issue

Tested with: 2019.3.0a8
Package version: 0.2.7
commit c231874

**Comment by todi1856** [comment]
This one was fixed long ago
