### ISSUE TITLE
Horizontal separators appearing randomly when multiple lines are selected

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#36]
![image](https://user-images.githubusercontent.com/43995107/60885601-a6c10480-a258-11e9-98d4-8488bda1a8bb.png)

![image](https://user-images.githubusercontent.com/43995107/60885609-a9235e80-a258-11e9-9559-0858d8b552e5.png)

Scrolling around makes them either appear or disappear, though always in the same place, like some hidden gems :) 

Tested with: 2019.3.0a8
Package version: 0.2.7
commit c231874

**Comment by todi1856** [comment]
This one seems to be fixed

**Comment by JuozasK** [comment]
Yeah, couldn't repro anymore

Tested on: MacOS
Package Version: 1.1.1
Unity 2020.2.0a5
