### ISSUE TITLE
Unnecessary space appeared after the search field

### ISSUE THREAD

**Issue by WashingMachinae** [Unity-Technologies/com.unity.mobile.logcat#45]
![image](https://user-images.githubusercontent.com/43995107/62861078-ff2d6b00-bd0a-11e9-8afd-d336567ef19d.png)

Should just be the search field and button separator there

Tested with:
Unity 2019.3.0a12
Package version: 1.0.0
Branch: bug-fixes
PR: #40

**Comment by todi1856** [comment]
Sadly it seems that's how Unity implements UnityEditor.IMGUI.Controls.SearchField

All other windows in Unity use EditorGUI.ToolbarSearchField but that's not exposed.

Doesn't look critical so I'll close it for now.
