### ISSUE TITLE
Device list shows Android 9 devices as version 0.0 (Failed to parse android OS version '9')

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#49]
![image](https://user-images.githubusercontent.com/43995107/67187631-4747c880-f3f3-11e9-98a2-703a3005681f.png)

![image](https://user-images.githubusercontent.com/43995107/67187686-6b0b0e80-f3f3-11e9-8092-60821cf22608.png)

Tested with #48  bug-fixes branch
Unity 2020.1.0a9

**Comment by todi1856** [comment]
fixed https://github.com/Unity-Technologies/com.unity.mobile.logcat/pull/48

**Comment by JuozasK** [comment]
Android OS versions now parsed correctly
Tested with #48 bug-fixes branch
commit a11859f
Unity 2020.1.0a9
