### ISSUE TITLE
Connecting via IP window should have a cancel button

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#50]
May be a minor issue, but I think in terms of usability this could use a "Cancel" button. 
![image](https://user-images.githubusercontent.com/43995107/67187922-f8e6f980-f3f3-11e9-9de0-a902005dd031.png)

Tested with #48 bug-fixes branch
Unity 2020.1.0a9

**Comment by todi1856** [comment]
Sorry, this operation is not cancelable, even if you'll click Cancel, this would only close the dialog, but underlying operation would still go n
