### ISSUE TITLE
Right clicking when Multiple lines are selected deselects everything except for the line being hovered over

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#51]
Expected result (Project window does this): If you have multiple items selected, right clicking opens context menu with all the lines still being selected
Actual result (Logcat window does this): If you have multiple items selected, right clicking selects just the one you were hovering over and then opens context menu
(You can hold shift to keep all the lines still selected, but I think it's very unintuitive)

![RightClickMultiSelect](https://user-images.githubusercontent.com/43995107/67190651-fc30b400-f3f8-11e9-9e1c-0cf08bccae59.gif)

Tested with #48 bug-fixes
Unity 2020.1.0a9

**Comment by todi1856** [comment]
fixed https://github.com/Unity-Technologies/com.unity.mobile.logcat/pull/48

**Comment by JuozasK** [comment]
Selecting lines seems to work as it does in project window now
Tested with #48 bug-fixes branch
commit a11859f
Unity 2020.1.0a9
