### ISSUE TITLE
There should be a way to "Disconnect" the stream so the user could inspect logs

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#52]
Use case:
If I got the logs that I wanted and want to examine them without lines flying away from me as new lines are added, I'd like to be able to stop the flow manually. Can we do that already or is it not an option?
This is when the max lines amount has been reached

Maybe a "Pause/Resume" button or something? 

![LinesFlyingAway](https://user-images.githubusercontent.com/43995107/67191039-a14b8c80-f3f9-11e9-8961-cff164e18795.gif)

**Comment by todi1856** [comment]
fixed https://github.com/Unity-Technologies/com.unity.mobile.logcat/pull/48

**Comment by JuozasK** [comment]
It's possible to stop the process now and inspect the logs with the "Disconnect" button 
Tested with #48 bug-fixes branch
commit a11859f
Unity 2020.1.0a9
