### ISSUE TITLE
Icons don't adhere to font size

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#53]
Small font makes icons overlap each-other
Big font makes icons look tiny

![IconsAndFontSize](https://user-images.githubusercontent.com/43995107/67193413-ef628f00-f3fd-11e9-9810-bdc02624d0a3.gif)

Expected: Icons should follow font size and get smaller or bigger

Tested with #48  bug-fixes branch
Unity version 2020.1.0a9

**Comment by todi1856** [comment]
fixed https://github.com/Unity-Technologies/com.unity.mobile.logcat/pull/48

**Comment by JuozasK** [comment]
Icons now hide when line gets too small to house them
Tested with #48 bug-fixes branch
commit a11859f
Unity 2020.1.0a9
