### ISSUE TITLE
Android Logcat Settings should be under "Analysis" tab

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#54]
![image](https://user-images.githubusercontent.com/43995107/67204914-3c9f2a80-f417-11e9-998a-f3ff99f2f08e.png)

Tested with #48  bug-fixes
Unity 2020.1.0a9

**Comment by todi1856** [comment]
fixed https://github.com/Unity-Technologies/com.unity.mobile.logcat/pull/48

**Comment by JuozasK** [comment]
Logcat settings are now under Analysis
Tested with #48  bug-fixes branch
 commit a11859fd088127cab230d32b12d3a91faa9f8d7c
Unity 2020.1.0a9
