### ISSUE TITLE
Icons are not centered in the middle of the cell

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#55]
They are top left anchored right now.
Should be in the center horizontally and vertically
![image](https://user-images.githubusercontent.com/43995107/67843484-bc5a8280-fb04-11e9-880e-7c57ca988939.png)

Tested with #48 bug-fixes branch
commit a11859f
Unity 2020.1.0a9

**Comment by JuozasK** [comment]
![image](https://user-images.githubusercontent.com/43995107/68213139-a99fec00-ffe3-11e9-9b1c-e50b1ea3df7c.png)
Icon is centered only horizontally, but not vertically

**Comment by todi1856** [comment]
This time it's really fixed

**Comment by JuozasK** [comment]
Icons are now centered vertically and horizontally

Tested with 68869003080463eee8e4ec5325c6c2006c5a9a34
Unity Version 2020.1.0a14
