### ISSUE TITLE
When hiding icons because of small font, the icon column should be hidden too

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#58]
![image](https://user-images.githubusercontent.com/43995107/68214564-5b401c80-ffe6-11e9-9017-6ad7037c3947.png)

Tested with #48 bug-fixes branch
commit 60993fd
Unity 2020.1.0a12

**Comment by todi1856** [comment]
Fixed, column is hidden

**Comment by JuozasK** [comment]
Column is hidden when icons are hidden

Tested with 68869003080463eee8e4ec5325c6c2006c5a9a34
Unity Version 2020.1.0a14
