### ISSUE TITLE
[Memory Window] Group dropdown unable to show entire group name

### ISSUE THREAD

**Issue by JuozasK** [Unity-Technologies/com.unity.mobile.logcat#82]
<img width="335" alt="Screenshot 2020-04-14 at 15 56 33" src="https://user-images.githubusercontent.com/43995107/79227499-a8170180-7e68-11ea-8738-8533359ad865.png">
See how "Proportional Set Size" is cut off.

Either make the middle separator resizeable or just extend it a little bit

Tested with #81 
Commit 93a29f75b9fa18c99a17fa49448f64a5e72d41b7 
Unity 2020.2.0a5

**Comment by todi1856** [comment]
will make horizontal separator

**Comment by todi1856** [comment]
Fixed

**Comment by JuozasK** [comment]
Checked with: 49cba39972b1df3a7ba135dae0b6b3151566e350
Fixed
