### ISSUE TITLE
Support library.address stacktrace format

### ISSUE THREAD

**Issue by rockwalrus** [Unity-Technologies/com.unity.mobile.logcat#97]
One of the devices I'm using has a stacktrace format that can't be used with the stacktrace utility. It produces logs with the following form:
```
     at libunity.00b2f4a0(Native Method)
```

A regex for this format can't be created because the code expects the first group to be the address and the second group to be the library name.

**Comment by todi1856** [comment]
This is now available in version 1.2.0
